name: SuperbVote
main: io.minimum.minecraft.superbvote.SuperbVote
author: tuxed
version: 0.3.1
depend: [Votifier]
softdepend: [PlaceholderAPI]
commands:
  superbvote:
    description: SuperbVote main command.
    aliases: [sv]
  vote:
    description: SuperbVote vote command.